# name: Deploy to S3
name: Deploy to VERCEL

on:
  push:
    branches:
      - main

env:
  # AWS_S3_BUCKET_STATIC: 'rocketseat-upload-widget-web-vitorh-static'
  # AWS_S3_BUCKET_CDN: 'rocketseat-upload-widget-web-vitorh-static-cdn'
  # SOURCE_DIST: './dist'
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets. VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Configure Node
        id: configure-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        id: install-pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Vercel
        id: install-vercel
        run: |
          npm install --global vercel@latest

      - name: Pull Vercel Config
        id: pull-vercel-config
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build App
        id: build-app
        run: |
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy APP
        id: deploy-app
        run: |
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
      
      # - name: Install Dependencies
      #   id: install-dependencies
      #   run: |
      #     pnpm install
      
      # - name: Build App
      #   id: build-app
      #   run: |
      #     pnpm run build
      
      # - name: Configure AWS Credentials
      #   id: configure-aws-credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{vars.AWS_REGION }}

      # - name: Sync file to S3 static
      #   id: sync-file-to-s3-static
      #   run: |
      #     aws s3 sync ${{ env.SOURCE_DIST }} s3://${{ env.AWS_S3_BUCKET_STATIC }}/ --delete

      # - name: Sync file to S3 CDN
      #   id: sync-file-to-s3-cdn
      #   run: |
      #     aws s3 sync ${{ env.SOURCE_DIST }} s3://${{ env.AWS_S3_BUCKET_CDN }}/ --delete

      # - name: Invalidate CDN Cache
      #   id: invalidate-cdn-cache
      #   run: |
      #     aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'

