name: Preview to Vercel

on:
  push:
    branches-ignore:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets. VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Configure Node
        id: configure-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        id: install-pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Vercel
        id: install-vercel
        run: |
          npm install --global vercel@latest

      - name: Pull Vercel Config
        id: pull-vercel-config
        run: |
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build App
        id: build-app
        run: |
          vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy APP
        id: deploy-app
        run: |
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}